name: On master push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  steps:
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
  
    - name: build-master
      uses: ./.github/workflows/build-reusable-workflow.yml
      with:
        version: ${{steps.package-version.outputs.current-version}}