name: On master push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  jobs:
    - uses: ./.github/workflows/build-reusable-workflow.yml
      name: 'run build workflow'