# This is a basic workflow to help you get started with Actions

name: Publish to chrome webstore

# Controls when the workflow will run
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish-to-chrome-webstore"
  publish-to-chrome-webstore:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-reusable-workflow.yml
        name: 'run build workflow'
        
      - uses: actions/download-artifact@v3
        name: 'Try to download the artifact from previous builds'
        with:
          name: 'dalle-chrome-ext.v${{ github.event.release.tag_name }}.zip'
      
      - name: Upload & release
        uses: mnao305/chrome-extension-upload@3.0.0
        with:
          file-path: 'dalle-chrome-ext.v${{ github.event.release.tag_name }}.zip'
          extension-id: 'hjhagfbhighhchddcbejligbanloandc'
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          draft: true #TODO: update the draft parameter based on type of release
